### ISSUE TITLE
odd errors when using docker container as my -t docker:// target

### ISSUE THREAD

**Issue by aaronlippold** [inspec/train#175]
When testing with the `dev-sec` postgresql hardening build I am able to use this other than I can use the vagrant ssh key and the -t option. ( Other than that, this should be the same use case )

```stig-postgres-baseline git:(master) ✗ inspec exec controls/V-73123.rb -t docker://bc7634a8664b --sudo --user=postgres --password=xxx```

```
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 5.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      logging (< 3.0, >= 1.6.1)
      docker-api (~> 1.26)
      thor (~> 0.19)
      addressable (~> 2.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.4.0/gems/train-0.23.0/lib/train/transports/docker.rb:61:in `initialize': undefined method `get' for Docker::Container:Class (NoMethodError)
    from /usr/local/lib/ruby/gems/2.4.0/gems/train-0.23.0/lib/train/transports/docker.rb:41:in `new'
    from /usr/local/lib/ruby/gems/2.4.0/gems/train-0.23.0/lib/train/transports/docker.rb:41:in `create_new_connection'
    from /usr/local/lib/ruby/gems/2.4.0/gems/train-0.23.0/lib/train/transports/docker.rb:22:in `connection'
    from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.20.0/lib/inspec/backend.rb:23:in `create'
    from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.20.0/lib/inspec/runner.rb:64:in `configure_transport'
    from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.20.0/lib/inspec/runner.rb:56:in `initialize'
    from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.20.0/lib/inspec/base_cli.rb:81:in `new'
    from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.20.0/lib/inspec/base_cli.rb:81:in `run_tests'
    from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.20.0/lib/inspec/cli.rb:159:in `exec'
    from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
    from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
    from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
    from /usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.20.0/bin/inspec:12:in `<top (required)>'
    from /usr/local/bin/inspec:22:in `load'
    from /usr/local/bin/inspec:22:in `<main>'```

**Comment by aaronlippold** [comment]
This was working two days ago ...

**Comment by aaronlippold** [comment]
OK I think I found the problem, I had the docker and docker-api gems installed as I was trying to get the kitchen-docker .kitchen.yml working. Once I removed those the problem went away. Is there some way to raise an error is the kitchen-dokken and docker and docker-api gems conflict with each other?

**Comment by aaronlippold** [comment]
So I am not sure if I should close this, or if it leads us to perhaps having a little better exception warnings.

**Comment by zenspider** [comment]
I think this is handled. If this is still an issue, please reopen.
