### ISSUE TITLE
Local transport on Windows creates LinuxFile instead of WindowsFile

### ISSUE THREAD

**Issue by tpcwang** [inspec/train#189]
InSpec's file resource behaves strangely when running locally on Windows because LinuxFile is used instead of WindowsFile. This causes various methods to fail with error like so:
```
>inspec shell -c "file(\"C:\\log\").type"
C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/profile_context.rb:144:in `instance_eval': undefined method `name' for nil:NilClass (NoMethodError)
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/train-0.26.1/lib/train/transports/local_file.rb:75:in `stat'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/train-0.26.1/lib/train/extras/file_unix.rb:49:in `block (2 levels) in <class:UnixFile>'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/resources/file.rb:52:in `call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/resources/file.rb:52:in `block (2 levels) in <class:FileResource>'
        from (eval):1:in `load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/profile_context.rb:144:in `instance_eval'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/profile_context.rb:144:in `load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/profile_context.rb:130:in `load_control_file'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/runner.rb:215:in `eval_with_virtual_profile'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/cli.rb:254:in `run_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/cli.rb:204:in `shell_func'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/bin/inspec:12:in `<top (required)>'
        from C:/opscode/inspec/bin/inspec:62:in `load'
        from C:/opscode/inspec/bin/inspec:62:in `<main>'
```

See [Train::Transports::Local::Connection.file](https://github.com/chef/train/blob/e10d65bc1fc828f27291956a5f574e0e5c44b7fc/lib/train/transports/local.rb#L43)
`@files[path] ||= File.new(self, path)`

Should there be conditional logic to create WindowsFile when running locally on Windows?

**Comment by kekaichinose** [comment]
Thank you for filing this issue. As with many large open source projects, we have a backlog of bugs and issues of varying user impact. Some issues are perpetually subject to lower priority than others in our backlog. We have reviewed the issue, and we have determined this a very low priority when considered in the context of the entire backlog. We have elected to close it as "Declined" due to competing priorities.

We very much appreciate you bringing this to our attention.

Thank you!
__Chef InSpec Team__
