### ISSUE TITLE
UUID unable to be detected on Windows 2012 R2/BM Server

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/train#319]
### Description

🐛 bug report

Splitting https://github.com/inspec/inspec/issues/3177

@reddeppas reports that running inspec on their Windows 2012 R2, BM Servers results in a stacktrace.  The stacktrace is clearly the UUID code failing.  No word on how the machines are managed.

### Train and Platform Version

inspec 2.2.20
train 1.4.11
Windows 2012 R2, BM Server

### Replication Case

Presumably any inspec shell or exec run targeting the platform.

### Stacktrace

```
opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.11/lib/train/platforms/detect/helpers/os_windows.rb:102:in windows_uuid_from_chef': undefined methodzero?' for nil:NilClass (NoMethodError)
from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.11/lib/train/platforms/detect/helpers/os_windows.rb:81:in windows_uuid' from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.11/lib/train/platforms/detect/uuid.rb:23:infind_or_create_uuid'
from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.11/lib/train/platforms/platform.rb:45:in uuid' from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.11/lib/train/platforms/platform.rb:52:in[]'
from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/resources/platform.rb:41:in []' from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/formatters/base.rb:190:inplatform'
from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.83/lib/inspec/formatters/base.rb:72:in stop' from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:206:inblock in notify'
from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in each' from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:innotify'
from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:199:in `stop'
from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:172:i
```

(trace appears cutoff in original ticket)

**Comment by karthikgooner** [comment]
Hello Cinton,

I also face this problem and unable to validate our Baremetal machines. Would you have any latest updates on this issue?

Stack trace:

[DEPRECATED] The option --format is being deprecated and will be removed in inspec 3.0. Please use --reporter
/usr/local/rvm/gems/ruby-2.4.1/gems/train-1.4.15/lib/train/platforms/detect/helpers/os_windows.rb:102:in `windows_uuid_from_chef': undefined method `zero?' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/train-1.4.15/lib/train/platforms/detect/helpers/os_windows.rb:81:in `windows_uuid'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/train-1.4.15/lib/train/platforms/detect/uuid.rb:23:in `find_or_create_uuid'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/train-1.4.15/lib/train/platforms/platform.rb:45:in `uuid'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/train-1.4.15/lib/train/platforms/platform.rb:52:in `[]'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-2.2.35/lib/resources/platform.rb:41:in `[]'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-2.2.35/lib/inspec/formatters/base.rb:190:in `platform'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-2.2.35/lib/inspec/formatters/base.rb:72:in `stop'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:206:in `block in notify'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `each'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `notify'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:199:in `stop'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:172:in `block in finish'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:191:in `close_after'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:171:in `finish'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `report'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-2.2.35/lib/inspec/runner_rspec.rb:77:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-2.2.35/lib/inspec/runner.rb:132:in `run_tests'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-2.2.35/lib/inspec/runner.rb:104:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-2.2.35/lib/inspec/cli.rb:171:in `exec'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-2.2.35/bin/inspec:12:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/inspec:23:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/inspec:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
