### ISSUE TITLE
unable to use -t azure:// from within docker container.

### ISSUE THREAD

**Issue by mmclane** [inspec/train#344]
### Description
When running inspec from within a docker container I get and error if I include -t azure://
```text
➭ docker run -i --rm -v "/Users/m.mclane/Repos/azure/terraform:/data" -w "/data/support/test/" [repository]/inspec:v1 inspec exec azure-infra-preprod -t azure://
/usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:165:in `initialize': Address not available - connect(2) for "localhost" port 50342 (Errno::EADDRNOTAVAIL)
        from /usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:165:in `new'
        from /usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:165:in `block in port_open?'
        from /usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from /usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:163:in `port_open?'
        from /usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:157:in `msi_auth?'
        from /usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:82:in `connect'
        from /usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:55:in `initialize'
        from /usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:25:in `new'
        from /usr/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/azure.rb:25:in `connection'
        from /usr/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/backend.rb:51:in `create'
        from /usr/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/runner.rb:66:in `configure_transport'
        from /usr/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/runner.rb:58:in `initialize'
        from /usr/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/cli.rb:170:in `new'
        from /usr/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/cli.rb:170:in `exec'
        from /usr/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:23:in `load'
        from /usr/bin/inspec:23:in `<main>'
```
If I leave off the azure target I don't get an error at all.

### Train and Platform Version

Versions:
OS: Linux a988e55989b1 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 Linux
Inspec: 2.2.70
Train: train-1.4.35

### Replication Case
DOCKERFILE:
```text
FROM microsoft/azure-cli

ARG VERSION=2.2.70
ARG GEM_SOURCE=https://rubygems.org

RUN mkdir -p /data
RUN apk add --update build-base libxml2-dev libffi-dev git openssh-client ruby ruby-dev && \
    gem install --no-document --source ${GEM_SOURCE} --version ${VERSION} inspec && \
    apk del build-base

# ENTRYPOINT ["inspec"]
# CMD ["help"]
VOLUME ["/data"]
WORKDIR /data
```

docker command run: 
docker run -i --rm -v "/Users/m.mclane/Repos/azure/terraform:/data" -w "/data/support/test/" crtouseprod.azurecr.io/inspec:v1 inspec exec azure-infra-preprod -t azure://

### Possible Solutions
Talking with stuart on the #inspec Channel in the chef community slack he said: 
"This looks like the code that tries to detect whether it's running inside an Azure VM with MSI support.  I don't think Docker provides a connection to localhost so this is probably a scenario that hasn't been considered and should be caught."

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by mmclane** [comment]
I hadn't added the right environment variable yet.  
I also found that if I removed localhost from the ipv6 line of my /etc/hosts file, it keeps this error from happening and I get an actual error from inspec instead telling me I was missing my Tenant_ID.

Either way, this should probably give a better error I would think.

Here is how I worked around it last night:
RUN sed 's/localhost ip6-localhost/ip6-localhost/g' > /tmp/hosts
RUN bash -c 'cat /tmp/hosts | tee -a /etc/hosts'
