### ISSUE TITLE
Train does not work with ED25519 keys

### ISSUE THREAD

**Issue by frezbo** [inspec/train#353]
### Description

Train does not work with ED25519 keys

#### Issue

Using a key generated with latest version of `ssh-keygen`

```
Traceback (most recent call last):
	38: from test.rb:68:in `<main>'
	37: from test.rb:68:in `new'
	36: from /home/frezbo/.bundle/ruby/2.5.0/gems/inspec-2.2.61/lib/inspec/runner.rb:58:in `initialize'
	35: from /home/frezbo/.bundle/ruby/2.5.0/gems/inspec-2.2.61/lib/inspec/runner.rb:66:in `configure_transport'
	34: from /home/frezbo/.bundle/ruby/2.5.0/gems/inspec-2.2.61/lib/inspec/backend.rb:51:in `create'
	33: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/transports/ssh.rb:81:in `connection'
	32: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/transports/ssh.rb:208:in `create_new_connection'
	31: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/transports/ssh.rb:208:in `new'
	30: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/transports/ssh_connection.rb:53:in `initialize'
	29: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/extras/command_wrapper.rb:128:in `load'
	28: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/plugins/base_connection.rb:95:in `platform'
	27: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect.rb:9:in `scan'
	26: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/scanner.rb:27:in `scan'
	25: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/scanner.rb:27:in `each'
	24: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/scanner.rb:33:in `block in scan'
	23: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
	22: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/scanner.rb:45:in `each'
	21: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/scanner.rb:46:in `block in scan_children'
	20: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/scanner.rb:46:in `instance_eval'
	19: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/specifications/os.rb:35:in `block in load'
	18: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/helpers/os_common.rb:43:in `unix_uname_s'
	17: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/platforms/detect/helpers/os_common.rb:36:in `command_output'
	16: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/plugins/base_connection.rb:103:in `run_command'
	15: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/transports/ssh_connection.rb:216:in `run_command_via_connection'
	14: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/transports/ssh_connection.rb:277:in `session'
	13: from /home/frezbo/.bundle/ruby/2.5.0/gems/train-1.4.37/lib/train/transports/ssh_connection.rb:178:in `establish_connection'
	12: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh.rb:246:in `start'
	11: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:71:in `authenticate'
	10: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:71:in `each'
	 9: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
	 8: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	 7: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:101:in `each_identity'
	 6: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:225:in `load_identities'
	 5: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:225:in `map'
	 4: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:232:in `block in load_identities'
	 3: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/key_factory.rb:44:in `load_private_key'
	 2: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/key_factory.rb:53:in `load_data_private_key'
	 1: from /home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/key_factory.rb:113:in `classify_key'
/home/frezbo/.bundle/ruby/2.5.0/gems/net-ssh-5.0.2/lib/net/ssh/authentication/ed25519_loader.rb:21:in `raiseUnlessLoaded': OpenSSH keys only supported if ED25519 is available (NotImplementedError)
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
Gem::LoadError : "ed25519 is not part of the bundle. Add it to your Gemfile."```

**Comment by clintoncwolfe** [comment]
From my reading of https://github.com/net-ssh/net-ssh/issues/565, it appears that net-ssh 5+ has such support.  train's current constraint is `net-ssh < 6.0, >= 2.9` which should cover that range, but I see our omnibus build is shipping 4.2.0, which makes the above needed gems optional.

So, it may be that a rebuild, possibly with a tighter constraint might fix that.  However, I'm not sure what else may be relying on net-ssh, which might be forcing the dependency down to 4.2.0

**Comment by frezbo** [comment]
@clintoncwolfe `net-ssh` also has a bug on how it identifies `ed25519` keys. Ref: https://github.com/net-ssh/net-ssh/issues/633

**Comment by miah** [comment]
This should be resolved with https://github.com/inspec/train/pull/435

**Comment by tas50** [comment]
So we had to back out the bit in #435, but train will utilize those gems if your require them. We're requiring them in chef/chef. We should make sure we have them in the inspec package as well. We can't ship them as required in the gemspec though because they require compilation tools on the host.
