### ISSUE TITLE
Some suggestion to extend support chef inspec to F5

### ISSUE THREAD

**Issue by ravitharanr** [inspec/train#376]
### Description

F5 base operating system is Centos 6.xx. On top of that, it run TMOS(tmsh) which customized OS of F5. However F5 allows us manage the device from base operating system as well as TMOS. So I'm thinking to use chef inspec for compliance check as chef inspec support for centos 6

Hit the platform detection had issues when i use ssh login which default to tmsh and was successful when i use ssh login to bash shell. 

F5 allows the user to switch from tmsh to bash shell vice versa.
Tmsh to Bash shell: run /util bash or bash

So is there anyway to work the platform detection for F5 by introducing something force the ssh connection/session change it from tmsh to bash before scan/detect the platform?

=======
Traceback (most recent call last):
        19: from C:/opscode/inspec/bin/inspec:108:in `<main>'
        18: from C:/opscode/inspec/bin/inspec:108:in `load'
        17: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.9/bin/inspec:12:in `<top (required)>'
        16: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        15: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        14: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        13: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        12: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.9/lib/inspec/cli.rb:181:in `exec'
        11: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.9/lib/inspec/cli.rb:181:in `new'
        10: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.9/lib/inspec/runner.rb:58:in `initialize'
         9: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.9/lib/inspec/runner.rb:66:in `configure_transport'
         8: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.0.9/lib/inspec/backend.rb:51:in `create'
         7: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.5.4/lib/train/transports/ssh.rb:81:in `connection'
         6: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.5.4/lib/train/transports/ssh.rb:208:in `create_new_connection'
         5: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.5.4/lib/train/transports/ssh.rb:208:in `new'
         4: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.5.4/lib/train/transports/ssh_connection.rb:53:in `initialize'
         3: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.5.4/lib/train/extras/command_wrapper.rb:128:in `load'
         2: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.5.4/lib/train/plugins/base_connection.rb:95:in `platform'
         1: from C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.5.4/lib/train/platforms/detect.rb:9:in `scan'
C:/opscode/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.5.4/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)

### Train and Platform Version
Train: inspec 3.0.9
==============
BIG-IP version | Custom built from operating system
-- | --
12.0.0 - 12.1.3 | CentOS 6.4 - 6.6, Linux Kernel 2.6.32 (64-bit kernel only)
===============

### Possible Solutions

If there is anyway to work the platform detection for F5 by introducing something force the ssh connection/session change it from tmsh to bash before scan/detect the platform, then it works.

**Comment by zenspider** [comment]
This is essentially adding a new platform to our support matrix. Not something I can make a call on. Assigning to keka to weigh in.

**Comment by miah** [comment]
We'll need hardware to do development against, though this can be emulated in GNS3; https://docs.gns3.com/appliances/f5-bigip.html

**Comment by Nargizzz** [comment]
I have the same issue. Was the feature implemented?
