### ISSUE TITLE
Fix GCP unit tests failing due to credentials file

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/train#393]
### Description

[test/unit/transports/gcp_test.rb](https://github.com/inspec/train/blob/master/test/unit/transports/gcp_test.rb) aborts with stacktrace when it occasionally cannot find a credentials file expected.  Happens sporadically on TravisCI, anecdotally on local.

Observed on #392 	

### Train and Platform Version

1.5.11

### Replication Case

Submit or update a PR, triggering a TravisCI run.

### Possible Solutions

Dunno.  Might be a race condition, does not appear consistently.

### Stacktrace

```
  1) Error:
gcp transport::gcp_compute_client#test_0001_test gcp_compute_client with caching:
RuntimeError: Unable to read the credential file specified by GOOGLE_APPLICATION_CREDENTIALS: file /tmp/application_default_credentials.json20181219-6986-wunbs2 does not exist
    /home/travis/build/inspec/train/vendor/bundle/ruby/2.5.0/gems/googleauth-0.6.7/lib/googleauth/credentials_loader.rb:94:in `rescue in from_env'
    /home/travis/build/inspec/train/vendor/bundle/ruby/2.5.0/gems/googleauth-0.6.7/lib/googleauth/credentials_loader.rb:83:in `from_env'
    /home/travis/build/inspec/train/vendor/bundle/ruby/2.5.0/gems/googleauth-0.6.7/lib/googleauth/application_default.rb:57:in `get_application_default'
    /home/travis/build/inspec/train/lib/train/transports/gcp.rb:90:in `connect'
    /home/travis/build/inspec/train/lib/train/transports/gcp.rb:44:in `initialize'
    /home/travis/build/inspec/train/lib/train/transports/gcp.rb:29:in `new'
    /home/travis/build/inspec/train/lib/train/transports/gcp.rb:29:in `connection'
    /home/travis/build/inspec/train/test/unit/transports/gcp_test.rb:47:in `block (2 levels) in <top (required)>'
```

From https://travis-ci.org/inspec/train/jobs/469920694

**Comment by clintoncwolfe** [comment]
Appears to have been fixed by #396
