### ISSUE TITLE
OS detection for NetApp

### ISSUE THREAD

**Issue by PopPopDevOps** [inspec/train#444]
### Description

Unable to run any Inspec tests against NetApp because it cannot determine the OS

### Train and Platform Version

Using Inspec version 3.6.6

### Replication Case

Try to run any test against a NetApp and it fails with:

```
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
```

### Stacktrace

```
inspec exec ./ldapnetapp.rb -t ssh://inspect@rdfascl111.rlab.discoverfinancial.com -i ~/.ssh/id_rsa

Traceback (most recent call last):
        19: from /usr/bin/inspec:122:in `<main>'
        18: from /usr/bin/inspec:122:in `load'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.6.6/bin/inspec:12:in `<top (required)>'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.6.6/lib/inspec/cli.rb:262:in `exec'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.6.6/lib/inspec/cli.rb:262:in `new'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.6.6/lib/inspec/runner.rb:58:in `initialize'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.6.6/lib/inspec/runner.rb:66:in `configure_transport'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.6.6/lib/inspec/backend.rb:52:in `create'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/transports/ssh.rb:81:in `connection'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/transports/ssh.rb:208:in `create_new_connection'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/transports/ssh.rb:208:in `new'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/transports/ssh_connection.rb:53:in `initialize'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/extras/command_wrapper.rb:128:in `load'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/plugins/base_connection.rb:109:in `platform'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/platforms/detect.rb:9:in `scan'

/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.2/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
```

**Comment by clintoncwolfe** [comment]
Unfortunately, unless hardware were to be made available, Chef would not be able to take on (eventual) maintainership of this, so we must decline this.

That said, you could create a Train transport plugin that would force detection; and you could maintain it.

Thanks!
