### ISSUE TITLE
Wrong raise error method arguments

### ISSUE THREAD

**Issue by vsingh-msys** [inspec/train#506]
# Version:
3.0.1

# Environment:
Host: Ubuntu 18.04
Target node: Centos 6.5
Protocol: SSH

# Scenario:
By default CentOS 6 is configured with `requiretty`
While hitting ssh with `sudo: true` getting backtrace error instead of a proper error message.

# Steps to Reproduce:
- SSH ready  any machine with(configure `requiretty`) or CentOS 6.5(default configured)
- Run 
```
train = Train.create('ssh', host: 'IP_ADDRESS', port: 22, user: 'user', password: 'password', sudo: true)
train.connection
```
# Expected Result:
```
Traceback (most recent call last):
	5: from ./test.rb:9:in `<main>'
	4: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/transports/ssh.rb:82:in `connection'
	3: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/transports/ssh.rb:238:in `create_new_connection'
	2: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/transports/ssh.rb:238:in `new'
	1: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/transports/ssh_connection.rb:53:in `initialize'
/.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/extras/command_wrapper.rb:173:in `load': Sudo failed: Sudo requires a TTY. Please see the README on how to configure sudo to allow for non-interactive usage. (Train::UserError)
```
# Actual Result:
```
Traceback (most recent call last):
	7: from ./test.rb:9:in `<main>'
	6: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/transports/ssh.rb:82:in `connection'
	5: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/transports/ssh.rb:238:in `create_new_connection'
	4: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/transports/ssh.rb:238:in `new'
	3: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/transports/ssh_connection.rb:53:in `initialize'
	2: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/extras/command_wrapper.rb:173:in `load'
	1: from /.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/extras/command_wrapper.rb:173:in `raise'
/.chefdk/gem/ruby/2.6.0/gems/train-3.0.1/lib/train/extras/command_wrapper.rb:173:in `set_backtrace': backtrace must be Array of String (TypeError)
```

**Comment by vsingh-msys** [comment]
Fixed in #508
