### ISSUE TITLE
InSpec / Train stacktraces on Windows/Habitat

### ISSUE THREAD

**Issue by miah** [inspec/train#518]
While testing the InSpec for Habitat/Windows package I noticed this bug:

```
PS C:\users\miah\projects\github\inspec> hab pkg exec miah/inspec inspec.bat detect
Traceback (most recent call last):
        20: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/bin/inspec:211:in `<main>'
        19: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/bin/inspec:211:in `load'
        18: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/inspec-bin-4.16.12/bin/inspec:11:in `<top (required)>'
        17: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/inspec-4.16.12/lib/inspec/base_cli.rb:33:in `start'
        16: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        15: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        14: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        13: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        12: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/inspec-4.16.12/lib/inspec/cli.rb:300:in `detect'
        11: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/inspec-4.16.12/lib/inspec/cli.rb:390:in `run_command'
        10: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/inspec-4.16.12/lib/inspec/cli.rb:390:in `new'
         9: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/inspec-4.16.12/lib/inspec/runner.rb:76:in `initialize'
         8: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/inspec-4.16.12/lib/inspec/runner.rb:84:in `configure_transport'
         7: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/inspec-4.16.12/lib/inspec/backend.rb:53:in `create'
         6: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/train-3.0.3/lib/train/transports/local.rb:17:in `connection'
         5: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/train-3.0.3/lib/train/transports/local.rb:17:in `new'
         4: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/train-3.0.3/lib/train/transports/local.rb:27:in `initialize'
         3: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/train-3.0.3/lib/train/transports/local.rb:42:in `select_runner'
         2: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/train-3.0.3/lib/train/plugins/base_connection.rb:116:in `platform'
         1: from C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/train-3.0.3/lib/train/platforms/detect.rb:9:in `scan'
C:/hab/pkgs/miah/inspec/4.16.12/20190917175855/vendor/gems/train-3.0.3/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
```

**Comment by miah** [comment]
I've actually verified that this problem exists when executing inspec outside of habitat as well. It happens when you run inspec in powershell, but not in cmd.

Powershell 5.1.18362.145
