### ISSUE TITLE
Regression: Train::Transports::SSH v3.8.5

### ISSUE THREAD

**Issue by deric4** [inspec/train#712]
# Version:

v3.8.5
#709 
93d72c46161a4c1e9ed5027f2e58741384613971
# Environment:

[Details about the environment such as the Operating System, cookbook details, etc...]

Noticed in multiple CI environments and developer stations late last week but following details from a Microsoft default ruby2.7 vscode devcontainer environment. 

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
```
# Scenario:

[What you are trying to achieve and you can't?]

Prior to this change (v3.8.1)  both inspec and kitchen-inspec were able to connect and execute against remote hosts using the AWS SSM session-manager-plugin via the SSH transport.  As of v3.8.5, this no longer seems supported.

# Steps to Reproduce:

1. Configure  `~/.ssh/config`
    ```ssh-config
    Host i-*
        StrictHostKeyChecking no
        ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
    ```
2. Run InSpec
    ```console
    $ inspec shell -t ssh://ubuntu@i-1223afsdsdfa  -i <path to private key>.pem  --diagnose -l debug
   ```
[If you are filing an issue what are the things we need to do in order to repro your problem?]

1. Install `aws-cli v2`
2. install `session-manager-plugin`
3. install inspec or test-kitchen/kitchen-inspec
4. configure ~/.ssh/config to connect to AWS EC2 instance (see above)
5. connect to instance using SSH transport

# Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]

SSH Transport supports previous functionality.

when pinning `train v3.8.1`
```console
$ inspec shell -t ssh://ubuntu@i-1223afsdsdfa -i <path to private key>.pem
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      ubuntu
    Families:  debian, linux, unix, os
    Release:   20.04
    Arch:      x86_64

inspec> 
```
 
# Actual Result:

[What actually happens after the reproduction steps?]

```console
$ inspec shell -t ssh://ubuntu@i-1223afsdsdfa  -i <path to private key>.pem
Traceback (most recent call last):
        39: from /usr/local/bundle/bin/inspec:23:in `<main>'
        38: from /usr/local/bundle/bin/inspec:23:in `load'
        37: from /usr/local/bundle/gems/inspec-bin-4.50.3/bin/inspec:12:in `<top (required)>'
        36: from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/base_cli.rb:35:in `start'
        35: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        34: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        33: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        32: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        31: from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/cli.rb:367:in `shell_func'
        30: from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/cli.rb:367:in `new'
        29: from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/runner.rb:79:in `initialize'
        28: from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/runner.rb:87:in `configure_transport'
        27: from /usr/local/bundle/gems/inspec-core-4.50.3/lib/inspec/backend.rb:38:in `create'
        26: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/transports/ssh.rb:86:in `connection'
        25: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/transports/ssh.rb:286:in `create_new_connection'
        24: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/transports/ssh.rb:286:in `new'
        23: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/transports/ssh_connection.rb:60:in `initialize'
        22: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/extras/command_wrapper.rb:190:in `load'
        21: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/plugins/base_connection.rb:123:in `platform'
        20: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect.rb:7:in `scan'
        19: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/scanner.rb:25:in `scan'
        18: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/scanner.rb:25:in `each'
        17: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/scanner.rb:31:in `block in scan'
        16: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/scanner.rb:43:in `scan_children'
        15: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/scanner.rb:43:in `each'
        14: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/scanner.rb:44:in `block in scan_children'
        13: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/scanner.rb:44:in `instance_eval'
        12: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/specifications/os.rb:20:in `block in load_windows'
        11: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/helpers/os_windows.rb:4:in `detect_windows'
        10: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/platforms/detect/helpers/os_windows.rb:9:in `check_cmd'
         9: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/plugins/base_connection.rb:149:in `run_command'
         8: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/transports/ssh_connection.rb:250:in `run_command_via_connection'
         7: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/transports/ssh_connection.rb:292:in `session'
         6: from /usr/local/bundle/gems/train-core-3.8.5/lib/train/transports/ssh_connection.rb:213:in `establish_connection'
         5: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
         4: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
         3: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:73:in `initialize'
         2: from /usr/local/lib/ruby/2.7.0/socket.rb:632:in `tcp'
         1: from /usr/local/lib/ruby/2.7.0/socket.rb:227:in `foreach'
/usr/local/lib/ruby/2.7.0/socket.rb:227:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
```

While this breaks `kitchen verify`, `inspec shell`, and `inspec exec`, test-kitchen is still able to create/login/destroy as before.

pinning to `train 3.8.1` for now.

**Comment by Vasu1105** [comment]
@deric4 Just want to know if you provide ssh config file path using the option does the things work?

**Comment by deric4** [comment]
Hi @Vasu1105 

I wasn't aware that such a flag existed 😅 but see you implemented the feature for that here https://github.com/inspec/inspec/pull/5759 just recently which is in `inspec v4.52.7`.

But that version hasn't been published to [rubygems.org]() so I'm only able to pull `inspec v4.50.3`

I'll try installing inspec from source and report back

**Comment by Vasu1105** [comment]
Yes @deric4 . It will be released soon. As we don't have the option to provide ssh config file path in InSpec we have first updated the train and then added the option in the InSpec. We just need to confirm does this works well when the option is provided, By default we are not reading the values from ssh config file unless the path is provided.

**Comment by deric4** [comment]
After some trial and error (wasn't able to configure bundler correctly due to  inspec  repo not having  a master branch),  I can confirm that `inspec 4.57.2` works with `inspec cli` when the `--ssh-config-file` is explicitly set to the path of the config file:

```console
$ inspec version
4.52.7

$ inspec shell -t ssh://ubuntu@<instance-id> -I <private key>.pem --ssh-config-file ~/.ssh/config 
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      ubuntu
    Families:  debian, linux, unix, os
    Release:   20.04
    Arch:      x86_64

inspec>
```

Still not clear to me how this is supposed to work with `kitchen-inspec`, I haven't been able to get a working example even when explicitly setting `proxy_command` in kitchen.yml.

Can you provide some insight as to when gems might be officially released along with documentation/examples of config changes that will need to take place in order to re-implement the behavior as of `train v3.8.1` for `kitchen-inspec`?

Thanks!

**Comment by Vasu1105** [comment]
Sure. I will check and let you know.
